name: Update README ⭐
on:
  push:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 373657
          year: 2021
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2021 --->
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 373657
          year: 2015
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2015 --->
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars